apiVersion: apps/v1
kind: Deployment
metadata:
  name: nilsholthues-web
  labels:
    app: nilsholthues-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nilsholthues-web
  template:
    metadata:
      labels:
        app: nilsholthues-web
    spec:
      containers:
        - name: web
          image: ghcr.io/slin86/nilsholthues-web:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
