apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/slin86/nilsholthues-web
  newName: ghcr.io/slin86/nilsholthues-web
  newTag: ea9610b020332f7485d0186d47940ad331fd8538
