apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/slin86/nilsholthues-web
  newName: ghcr.io/slin86/nilsholthues-web
  newTag: af639e237954d8e1d739bdcfa9fd61f3dafc80eb
