apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/slin86/nilsholthues-web
  newName: ghcr.io/slin86/nilsholthues-web
  newTag: 3bbabc87c8601a95bf7c6c496d09978254d20d12
